"""NAMED-REGRESSION TRIPWIRE for public copy. NOT a proof that the copy is safe.

READ THIS BEFORE TRUSTING A PASS. This file catches *specific phrasings this
project has already got wrong*. It does not understand English, it does not
evaluate whether a sentence is supported by an artifact, and it will not catch a
novel overclaim. Two Gate A audits proved that empirically: the first version
passed the whole repository while two violations sat in `lab.py`, and the second
passed while the retracted default-prevention claim was live on both the README
and the landing page in a paraphrase.

**The real gate is human review against `research/CLAIM_LEDGER.md`.** This file
is a tripwire that stops known-bad strings from coming back. Treat a pass as
"no *named* regression", never as "the copy is accurate".

Scanner work is deliberately time-boxed. Do not grow this into a natural-language
verification system; that is the ledger review's job.

Every pattern here corresponds to a specific claim this project made and had to
retract. The test is not stylistic. Each phrase, in the absence of a qualifier,
asserts something the artifacts do not support:

  "instead of defaulting"   — revenue-contingency extends the term; it does not
                              prevent non-recovery. `closure_m7` is 100.0%
                              incomplete at BOTH registered cap factors.
  "conventional/market"     — the 18% nominal, 12-month benchmark is an assumed
                              input. No market survey backs it. Calling it
                              conventional implies a sourced rate.
  "confidence interval"     — the intervals are Monte Carlo intervals over
                              simulated paths. They carry no information about
                              real sellers (D-014, CORRECTED_CLAIMS #4).
  "equal cost"              — the cap factor f* was solved on ONE flat,
                              shock-free reference path. On simulated paths the
                              realised rate differs. "Reference-path
                              cost-matched" is the accurate name.
  "2.3x the interest"       — retracted by D-015 / DERIVATIONS P6: the
                              contractual repayment target A·f is proportional
                              to f (and realised repayment equals it only upon
                              completion), so a ratio quoted at the
                              illustrative f = 1.20 is a pricing result, not a
                              property of revenue-based repayment.
  "0.92 AUC"                — circular: the label was generated by a formula
                              over the same features (D-001).

DESIGN NOTE — why negation windows rather than a flat ban. Most of these
phrases MUST be sayable in order to disown them; a page that cannot print the
words "confidence interval" cannot tell the reader these are not confidence
intervals. So an occurrence passes when a disowning cue sits near it, and fails
when it stands alone. That keeps the honest usage legal and the assertive usage
failing.

The historical allow-list is deliberately narrow and is itself tested: an audit
document earns its exemption only by carrying a supersession banner. Otherwise
"it's historical" becomes the loophole that lets a retracted claim stay live.
"""
import glob
import os
import re

import pytest

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

#: Surfaces a reader or reviewer encounters as current claims.
#:
#: `frontend/*.html` is GLOBBED, not listed. A static list silently excludes any
#: page added later — and a new public page is exactly where an unreviewed claim
#: would land.
def _live_surfaces():
    fixed = [
        "README.md",
        "RESEARCH_MANIFEST.md",
        "backend/lab.py",
        "backend/main.py",            # public API strings reach users too
        "backend/money.py",
        "backend/financing_engine.py",
        "research/rbf_sim/README.md",
        "research/METRIC_DEFINITIONS.md",
    ]
    pages = sorted(
        os.path.relpath(p, REPO)
        for p in glob.glob(os.path.join(REPO, "frontend", "**", "*.html"),
                           recursive=True))
    return tuple(fixed + pages)


LIVE_SURFACES = _live_surfaces()

#: Audit-trail documents. Exempt ONLY because they record what was believed and
#: why it changed. Each must carry a supersession/correction banner — asserted
#: by test_historical_documents_carry_a_supersession_banner below.
#: Exempt from the LIVE scan, but NOT unexamined — see
#: test_allow_listed_documents_do_not_hide_an_unmarked_claim, which requires
#: every forbidden phrase in these files to sit beside a supersession marker.
#:
#: `RESULTS_REGISTRY.md` and `BACKLOG.md` were previously blanket-exempted as
#: "historical". That was too generous: the registry is also the document that
#: decides what may be quoted, so a stale authorization there is a live defect.
#: They are now exempt only from the phrase scan, never from the marker check.
HISTORICAL = (
    "research/BASELINE_FINDINGS.md",
    "research/CORRECTED_CLAIMS.md",
    "research/PHASE0_AUDIT.md",
    "research/DECISION_LOG.md",
    "research/RESULTS_REGISTRY.md",
    # The ledger quotes every retracted phrase in its §6 in order to forbid
    # them. Scanning it as live would fail on its own withdrawal list.
    "research/CLAIM_LEDGER.md",
    "research/BACKLOG.md",
)

#: Frozen inputs. Editing these would desynchronise the spec version string
#: embedded in every canonical artifact, and P1-P7 are load-bearing proofs.
FROZEN = (
    "research/METHODOLOGY_SPEC.md",
    "research/DERIVATIONS.md",
)

#: Cues that turn an assertion into a disavowal.
#:
#: DIRECTIONAL AND TIGHT, and the first version of this test was neither. It
#: used a 240-char symmetric window including bare "not", which in dense
#: technical prose disowns essentially every match — the scanner passed the
#: whole repository while the very violations it was written for sat in
#: `lab.py` untouched. A scanner that cannot fail on the text that motivated it
#: is worse than no scanner, because it certifies.
#:
#: English disavowals put the negation immediately BEFORE the term ("this is
#: NOT a confidence interval") or a correction marker immediately AFTER
#: ("...conventional loan" — SUPERSEDED"). So: short windows, both sides.
#: A bare "not " is NOT in this list, deliberately. An audit measured the
#: damage: with bare "not " at a 90-char window, 24.6% of README insertion
#: points already sat inside a pre-disowned zone, and every one of nine
#: assertive sentences slipped through simply by being preceded by an ordinary
#: unrelated clause — e.g. "Fees are not modelled. Benchmark B is a
#: conventional loan priced at 18% nominal." A negation that is not ABOUT the
#: matched phrase is not a disavowal of it, it is a coincidence.
#:
#: So every cue here must bind the negation to the term itself, and the window
#: is short enough that it has to sit adjacent.
NEGATION_BEFORE = (
    "not a ", "not an ", "not the ", "not population ", "not quotable",
    "n't a ", "never a ", "no longer a ", "rather than a ", "must not ",
    "~~", "do not quote", "stop saying", "avoid saying", "instead of a ",
    "not \"", "not '", "not *", "not **",
    # Comparative disavowal: "a stronger signal than any confidence interval
    # would be" argues against using the thing it names.
    "than any ", "than a ", "unlike a ", "unlike the ",
)
NEGATION_AFTER = (
    "supersede", "retract", "withdraw", "corrected", "was wrong", "is wrong",
    "demote", "circular", "do not quote", "no longer", "~~",
    "— retracted", "- retracted", "my own error", "was my error",
)
#: 20, not 48 and certainly not 240. At 48 the sentence "This is a simulation,
#: not a forecast, and the structure is proven safe for providers" still
#: passed: "not a " sat 38 characters from "proven safe", negating *forecast*
#: and disowning a different claim entirely. A disavowal has to be adjacent to
#: the thing it disowns — "NOT a confidence interval" puts the cue at distance
#: zero. If a qualifier is further away than this, the sentence should be
#: rewritten so the reader gets the qualifier too.
WINDOW_BEFORE = 20
WINDOW_AFTER = 60

#: (regex, why it is banned). Case-insensitive.
#: Patterns are written to catch the FAMILY, not the one sentence that
#: motivated them. An audit of the first version found the two most relevant
#: regexes could not match the wording actually in the repo: the literal
#: `instead of defaulting` missed "instead of triggering a default" on both the
#: README and the landing page, and `equal effective cost` (spaces) missed
#: "equal-effective-cost" (hyphens), which is the only spelling this project
#: uses. Both live violations survived a passing scan. Hence: plurals, tenses,
#: passive voice and hyphen variants below.
FORBIDDEN = (
    (r"instead of (?:defaulting|triggering a default|a default|default\b)|"
     r"rather than (?:defaulting|triggering a default)|"
     r"\bwithout (?:triggering a )?defaulting?\b",
     "asserts revenue-contingency prevents default; closure_m7 is 100% incomplete"),
    (r"\bprevents? default|\bavoids? default|\bnever defaults?|\bcannot default|"
     r"\beliminates? default|\bdefault (?:is|becomes) impossible|"
     r"\bprotects? (?:sellers?|the seller) from default|\bno default risk|"
     r"\bnever fall(?:s)? into arrears|\bcan never default|\bno principal loss",
     "no default model exists in this study; non-recovery is mechanical"),
    (r"\bconventional loans?\b|\bconventional \d+-month\b|"
     r"\b(?:standard|typical|normal|ordinary) (?:\d+-month )?"
     r"(?:bank )?(?:amortizing )?loan\b",
     "the 18% benchmark is an assumed input, not a sourced market rate"),
    (r"\bmarket[- ]rates?\b|\bmarket APR\b|\bprevailing rate|"
     r"\brealistic (?:18|loan|rate|alternative)|\bexternally cited market",
     "implies an externally sourced rate; none was sourced"),
    (r"confidence intervals?\b|\bbootstrap CIs?\b|\b95% CIs?\b",
     "intervals are Monte Carlo over simulated paths, not population CIs"),
    (r"\bequal[- ]cost\b|\bequal[- ]effective[- ]cost\b|\bequal effective cost\b",
     "say 'reference-path cost-matched'; f* was solved on one flat path"),
    (r"2\.3\s*(?:[x×]|times)\s*(?:the\s*)?interest",
     "retracted by D-015 / DERIVATIONS P6 as a price-structure conflation"),
    (r"0\.92\s*AUC|AUC\s*(?:of\s*)?0\.92",
     "circular metric; label generated by a formula over the same features"),
    # Scoped to OUTCOME guarantees, and BIDIRECTIONAL. `money.settle`
    # legitimately guarantees a code invariant (`sum(settle(...)) <= cap_vnd`),
    # proven by test and mutation-tested; banning that sense would punish a
    # true statement. But a forward-only lookahead let passive voice through —
    # "Recovery of the full cap is guaranteed on every path" — so the outcome
    # word is now accepted on either side.
    # Python lookbehind must be fixed-width, so passive voice is caught by a
    # plain pattern instead: "Recovery of the full cap IS GUARANTEED on every
    # path" defeated the forward-only lookahead. `money.settle` says
    # "Guarantees `sum(...)`", never "is guaranteed", so the true code
    # invariant is untouched by this alternative.
    (r"\b(?:is|are|was|were) guaranteed\b|"
     r"\bguarantees?d?\b(?=[^.]{0,90}(?:repay|recover|return|profit|outcome|"
     r"default|safe|cheap|afford))",
     "no seller- or provider-outcome is guaranteed on any path"),
    (r"\balways repays?\b|\brepaid in full\b|\brecovers? in full\b|"
     r"\brepays? in full\b(?! (?:only|when|where))",
     "full repayment is scenario- and horizon-conditional"),
    (r"\bproven safe\b|\bsafe for (?:providers|sellers)\b|"
     r"\bduration risk, not principal loss\b",
     "no safety claim is supported by simulated mechanics"),
    (r"\bimmune to under[- ]?reporting\b|\bimmune to revenue\b",
     "invariance is contractual; the value judgement does not follow (CORRECTED_CLAIMS #3)"),
    (r"\b5\.77%\s*(?:cap[- ])?overshoot|\bcap overshoot of 5\.77",
     "my own retracted error; 0 breaches in 6,794 structures (D-029)"),
    # ── Gate A round 2 (D-040 / D-041) ──────────────────────────────────────
    (r"\bno CIC (?:record|file)\b|\bmost vietnamese sellers have no\b|"
     r"\bCIC (?:coverage|prevalence)\b",
     "no CIC prevalence data exists in this project"),
    (r"\bricher(?:,| )?(?:[a-z -]{0,30})?dataset than any bureau|"
     r"\bricher behavioral dataset\b|\bbetter than (?:a |any )?bureau\b|"
     r"\bbest credit data\b",
     "no comparison against bureau data was performed"),
    (r"\bthird[- ]party verified\b|\bupdated daily\b",
     "platform verification cadence was never audited by this project"),
    (r"\bin under a second\b|\bone API call in under\b|\bsub[- ]second\b",
     "no latency benchmark exists"),
    (r"common (?:for|in) [a-z, ]{0,40}categor|typical (?:for|of) [a-z, ]{0,40}"
     r"categor|\bfashion and gift\b",
     "scenario shapes are specified inputs, not observed category patterns"),
    (r"\bdefault probability\b(?![^.]{0,60}(?:synthetic|demo|not validated))",
     "the model score is circular and is not a validated PD"),
    (r"\bbit[- ]identical to RBF\b|\bRBF-G (?:is |was )?identical to RBF\b|"
     r"\bguardrails never bind\b",
     "false: the ceiling binds in 6 of 10 scenarios (D-040)"),
    # The exclusion list here originally contained the bare word "platform",
    # which meant the sentence "reproduce byte-for-byte on every platform" —
    # the exact overclaim — disabled its own pattern. Exclusions must be
    # narrower than the thing they exempt.
    # Intervening words allowed: "reproduce IT byte-for-byte" and "reproduce
    # EACH byte-for-byte" both slipped a version that demanded adjacency, and
    # both were live in `lab.py` and `lab.html`.
    (r"reproduces?\s+(?:\w+\s+){0,3}byte[- ]for[- ]byte(?![^.]{0,140}"
     r"(?:on linux|within a|within the|in the tested|three of five|"
     r"fixed runtime|same runtime))|"
     r"byte[- ]identical (?:on|across) (?:every|all|any)\b|"
     r"byte[- ]for[- ]byte on (?:every|all|any)\b|"
     # `bit-for-bit` is the same claim in different words, and was live in
     # `rbf_sim/README.md` and the spec while the scanner watched only for
     # `byte`. A tripwire that misses a synonym is a tripwire with a gap.
     r"\bbit[- ]for[- ]bit\b(?![^.]{0,140}"
     r"(?:withdrawn|too strong|within a|fixed runtime|D-041))",
     "byte equality is platform-dependent; 9 and 2 last-bit diffs on macOS (D-041)"),
    (r"burden rises (?:exactly )?in proportion\b",
     "fixed burden rises in INVERSE proportion to revenue"),
    (r"\bextended instead of missed\b|\bextended rather than missed\b",
     "asserts the contract is always ultimately repaid"),
    (r"Vietnam[- ]calibrated\b|calibrated to Vietnam",
     "no parameter was estimated from Vietnamese data (A-8)"),
    (r"would (?:a seller )?realistically be offered\b|"
     r"what a seller would be offered\b",
     "the offer set facing this population was never surveyed (A-8)"),
    (r"platforms settle after returns\b(?![^.]{0,80}(?:pending|unverified))",
     "no platform settlement documentation was obtained (A-8)"),
    (r"real RBF contracts commonly\b|commonly carry a maturity date\b",
     "no market survey of RBF terms was conducted (A-8)"),
    (r"\bestimates are converged\b|\bthe study is converged\b|"
     r"\bconverged\b(?=[^.]{0,40}(?:across the study|everywhere))",
     "convergence was checked for two estimators on one scenario only"),
)


def _read(rel):
    with open(os.path.join(REPO, rel), encoding="utf-8") as fh:
        return fh.read()


def _join(s):
    """Undo Python adjacent-string-literal splitting, then collapse whitespace.

    `"...NOT a "\n    "confidence interval..."` is one string to the reader and
    to the API; only the source file has the quotes and indentation in between.
    """
    s = re.sub(r"['\"]\s*\+?\s*['\"]", "", s)   # "..." "..."  and  "..." + "..."
    return re.sub(r"\s+", " ", s)


def _plain(s):
    """Drop markdown emphasis so `not ** a claim` reads as `not a claim`.

    Without this, bolding a negation silently disables it — the cue would be
    looking for "not a " in text that says "not** a ".
    """
    return re.sub(r"[*_`~]+", "", s).replace("  ", " ").lower()


def _disowned(text, start, end):
    """True when a disavowal cue sits tight against the match, on either side."""
    # Take a generous raw window, remove Python string-concatenation joins and
    # collapse whitespace, THEN clip to the tight window. Scanning .py source
    # means an adjacent qualifier can be separated from its term by `" \n
    # <28 spaces> "` — the reader sees "NOT a confidence interval", the scanner
    # saw 30 characters of quotes and indentation and called it undisowned.
    raw_before = _join(text[max(0, start - WINDOW_BEFORE * 6):start])[-WINDOW_BEFORE:]
    raw_after = _join(text[end:end + WINDOW_AFTER * 6])[:WINDOW_AFTER]
    # Strikethrough is checked on the RAW text: `_plain` strips `~`, so asking
    # for "~~" in the plain form could never match.
    if "~~" in raw_before or "~~" in raw_after:
        return True
    before, after = _plain(raw_before), _plain(raw_after)
    word_cues_before = [c for c in NEGATION_BEFORE if c != "~~"]
    word_cues_after = [c for c in NEGATION_AFTER if c != "~~"]
    return (any(_plain(c) in before for c in word_cues_before)
            or any(_plain(c) in after for c in word_cues_after))


@pytest.mark.parametrize("rel", LIVE_SURFACES)
def test_live_surfaces_do_not_overclaim(rel):
    path = os.path.join(REPO, rel)
    if not os.path.exists(path):
        pytest.skip(f"{rel} absent")
    text = _read(rel)
    violations = []
    for pattern, why in FORBIDDEN:
        for m in re.finditer(pattern, text, re.IGNORECASE):
            if _disowned(text, m.start(), m.end()):
                continue
            line = text.count("\n", 0, m.start()) + 1
            snippet = text[max(0, m.start() - 70):m.end() + 70].replace("\n", " ")
            violations.append(f"{rel}:{line}  {m.group(0)!r} — {why}\n      …{snippet}…")
    assert not violations, (
        "unqualified claim(s) on a public surface:\n  " + "\n  ".join(violations))


#: Allow-listed documents that nevertheless carry CURRENT authority, and so get
#: the per-phrase marker check rather than only the document-level banner.
#:
#: The registry decides what may be quoted; the backlog decides what gets built.
#: A stale claim in either is live, whatever the file's classification says. The
#: pure audit-trail documents (`CORRECTED_CLAIMS`, `DECISION_LOG`,
#: `PHASE0_AUDIT`, `BASELINE_FINDINGS`) exist precisely to restate wrong claims
#: at length, so per-phrase marking there produces noise, not signal — they are
#: covered by the banner test below.
#: `CLAIM_LEDGER.md` is here despite quoting every retracted phrase in its §6:
#: it is the document that governs what may be said, so an unmarked claim in it
#: is maximally live. Its §6 quotations sit beside "withdrawn"/"retracted"
#: markers and pass; an unmarked assertion — as P-4's settlement premise was —
#: does not.
AUTHORITATIVE = ("research/RESULTS_REGISTRY.md", "research/BACKLOG.md",
                 "research/CLAIM_LEDGER.md")


@pytest.mark.parametrize("rel", AUTHORITATIVE)
def test_allow_listed_documents_do_not_hide_an_unmarked_claim(rel):
    """Exemption from the LIVE scan is not exemption from scrutiny.

    A forbidden phrase in a document that still governs what may be quoted is
    acceptable only where it is visibly marked as superseded or retracted.
    Without this, the allow-list is just a place to hide a claim — which is how
    the registry came to carry a retracted authorization through two audits.
    """
    path = os.path.join(REPO, rel)
    if not os.path.exists(path):
        pytest.skip(f"{rel} absent")
    text = _read(rel)
    unmarked = []
    for pattern, why in FORBIDDEN:
        for m in re.finditer(pattern, text, re.IGNORECASE):
            if _disowned(text, m.start(), m.end()):
                continue
            # Wider window here: these documents mark supersession at the row
            # or paragraph level rather than inline.
            ctx = _plain(_join(text[max(0, m.start() - 500):m.end() + 500]))
            # The ledger's idiom for forbidding a phrase is to quote it and say
            # "never", "do not", or "counterexample to" — not to strike it. And
            # a correctly *conditional* use ("repaid in full only if the cap is
            # reached") is the thing this project spent Gate A adding, so
            # conditional markers count as marking.
            if any(c in ctx for c in ("supersede", "retract", "withdraw",
                                      "corrected", "do not quote", "demote",
                                      "was wrong", "no longer", "historical",
                                      "audit trail", "false", "counterexample",
                                      "never ", "do not ", "must not",
                                      "only if", "only where", "only matters",
                                      "conditional", "not a claim")):
                continue
            line = text.count("\n", 0, m.start()) + 1
            unmarked.append(f"{rel}:{line}  {m.group(0)!r} — {why}")
    assert not unmarked, (
        "forbidden phrase in an allow-listed document with NO supersession "
        "marker anywhere near it:\n  " + "\n  ".join(unmarked))


@pytest.mark.parametrize("rel", HISTORICAL)
def test_historical_documents_carry_a_supersession_banner(rel):
    """The exemption is earned, not granted.

    Without this, adding a file to HISTORICAL would be enough to smuggle a
    retracted claim back onto a surface a reader treats as current.
    """
    path = os.path.join(REPO, rel)
    if not os.path.exists(path):
        pytest.skip(f"{rel} absent")
    head = _read(rel)[:4000].lower()
    # Stems, not inflections. DECISION_LOG.md's banner reads "supersede them
    # with a new entry" — an earlier version of this list checked "superseded"
    # and "supersedes" and missed it by one character.
    cues = ("supersede", "correct", "retract", "withdraw",
            "audit trail", "do not quote", "demote", "historical", "append-only")
    assert any(c in head for c in cues), (
        f"{rel} is allow-listed as historical but its opening carries no "
        f"supersession/correction banner. Either add one or remove it from "
        f"HISTORICAL — the allow-list must not become a loophole.")


def test_frozen_documents_are_not_in_the_live_or_historical_lists():
    """The spec and the derivations are inputs, not scanner targets.

    Their version strings are embedded in every canonical artifact and P1-P7
    are referenced by the derivation tests, so a blind scan-and-rewrite across
    them would silently invalidate registered results.

    This protects them from *automated* rewriting. It does not make them
    immutable: a logged, reviewed, checksum-neutral editorial correction is
    legitimate and has happened -- D-047 and D-048 corrected prose in
    DERIVATIONS.md and CLAIM_LEDGER.md with no formula, generator or artifact
    change, and A-9/D-049 amended the spec deliberately after a genuine
    implementation defect was demonstrated. The rule is that such a change goes
    through the decision log and states its artifact impact, not that it never
    happens.
    """
    for rel in FROZEN:
        assert rel not in LIVE_SURFACES, f"{rel} is frozen; do not scan-and-edit it"
        assert rel not in HISTORICAL, f"{rel} is frozen; do not scan-and-edit it"


#: The exact sentences this repository actually shipped, before D-037 removed
#: them. Verbatim, with their real surrounding context — a scanner tuned on
#: toy strings proves nothing about behaviour on dense prose, which is how the
#: first version of this file came to pass while the violations were live.
RETRACTED_COPY = (
    ('"why": "Revenue-based repayment extends the term when revenue falls "\n'
     '       "instead of defaulting. The extension is the provider\'s cost.",',
     "lab.py METRIC_DEFINITIONS.duration_months_mean"),
    ('"note": "A conventional 12-month amortizing loan at 18% nominal annual "\n'
     '        "rate. Not cost-matched; it is the external price reference."},',
     "lab.py ARMS FIX-B"),
    ("RBF at `f = 1.20` over a 12-month base case costs roughly 2.3x the "
     "interest of an 18% conventional loan. Mean payment burden is "
     "correspondingly higher for FIX-A (10.2%) than FIX-B (9.4%).",
     "BASELINE_FINDINGS F-2"),
)


@pytest.mark.parametrize("text,origin", RETRACTED_COPY)
def test_scanner_catches_the_copy_this_project_actually_retracted(text, origin):
    """The scanner must fail on the real sentences, not just on toy ones.

    This is the test that would have caught the first version of this file,
    whose negation window was so wide that `lab.py` scanned clean while both
    violations were still in it.
    """
    hits = [(p, w) for p, w in FORBIDDEN
            for mm in [re.search(p, text, re.IGNORECASE)] if mm
            and not _disowned(text, mm.start(), mm.end())]
    assert hits, (
        f"scanner does NOT catch retracted copy from {origin} — it would have "
        f"certified this text as safe:\n  {text}")


#: Sentences that DEFEATED an earlier version of this scanner. Each pairs an
#: overreaching claim with an ordinary unrelated negation in the preceding
#: clause — which is all it took, when a bare "not " counted as a disavowal.
#: Plus the hyphen/plural/tense/voice variants the patterns originally missed.
EVASIONS = (
    "Fees are not modelled. Benchmark B is a conventional loan priced at 18% nominal.",
    "We do not report medians here. The reported band is a 95% confidence interval.",
    "Growth is not compounded. At the equal cost cap the two products are priced identically.",
    "The generator cannot produce negative revenue, and the settlement rule "
    "guarantees full repayment to the provider.",
    "This is a simulation, not a forecast, and the structure is proven safe for providers.",
    "A slow month extends the term instead of triggering a default.",
    "At the equal-effective-cost factor the products match on price.",
    "The model reflects prevailing market rates for Vietnamese sellers.",
    "Every contract repaid in full.",
    "The provider recovers in full in every scenario.",
    "Recovery of the full cap is guaranteed on every path.",
    "RBF costs 2.3 times the interest of the benchmark.",
    "Fixed payments are immune to underreporting.",
    "Providers face no principal loss.",
    "The structure eliminates default risk for the seller.",
    # Gate A round 2: the exact live claims corrected at D-040/D-041.
    "Most Vietnamese sellers have no CIC record.",
    "Platform data is a richer behavioral dataset than any bureau provides.",
    "Platform revenue is timestamped, third-party verified, and updated daily.",
    "The whole analysis returns through one API call in under a second.",
    "Pronounced peaks and troughs — common for fashion and gift categories.",
    "Default probability 2.4% for this seller.",
    "RBF-G is bit-identical to RBF in all ten scenarios.",
    "All five artifacts reproduce byte-for-byte on every platform.",
    "A fixed instalment's burden rises exactly in proportion as revenue falls.",
    "Under a revenue share repayment is extended instead of missed.",
    "Findings hold in a Vietnam-calibrated parameter range.",
    "Benchmark B answers what a seller would realistically be offered instead.",
    "Platforms settle after returns, so GMV overcharges.",
    "Real RBF contracts commonly carry a maturity date.",
    "The equal-effective-cost cap is f* = 1.0945.",
    "Estimates are converged across the study.",
)


@pytest.mark.parametrize("sentence", EVASIONS)
def test_scanner_catches_known_evasions(sentence):
    """Each of these passed a previous version of this file. None may again."""
    hit = any(mm and not _disowned(sentence, mm.start(), mm.end())
              for p, _ in FORBIDDEN
              for mm in [re.search(p, sentence, re.IGNORECASE)])
    assert hit, f"evasion slipped through the scanner:\n  {sentence}"


def test_a_bare_negation_in_an_unrelated_clause_does_not_disown():
    """The specific defect: a negation must be ABOUT the phrase, not merely near it."""
    s = "Fees are not modelled. Benchmark B is a conventional loan priced at 18%."
    m = re.search(r"\bconventional loans?\b", s, re.IGNORECASE)
    assert m and not _disowned(s, m.start(), m.end()), (
        "an unrelated 'not' in a preceding clause is disowning the match again")


def test_negation_cues_do_not_disown_an_undisowned_sentence():
    """The other failure direction: cues so broad nothing ever fails."""
    planted = ("Revenue-based repayment extends the term when revenue falls "
               "instead of defaulting, and is cheaper than a conventional loan.")
    m = re.search(FORBIDDEN[0][0], planted, re.IGNORECASE)
    assert m and not _disowned(planted, m.start(), m.end()), \
        "NEGATION cues are too broad — they disown an undisowned sentence"
