"""Public copy may not overclaim — a scanner for the phrases we got wrong before.

Every pattern here corresponds to a specific claim this project made and had to
retract. The test is not stylistic. Each phrase, in the absence of a qualifier,
asserts something the artifacts do not support:

  "instead of defaulting"   — revenue-contingency extends the term; it does not
                              prevent non-recovery. `closure_m7` is 100.0%
                              incomplete at BOTH registered cap factors.
  "conventional/market"     — the 18% nominal, 12-month benchmark is an assumed
                              input. No market survey backs it. Calling it
                              conventional implies a sourced rate.
  "confidence interval"     — the intervals are Monte Carlo intervals over
                              simulated paths. They carry no information about
                              real sellers (D-014, CORRECTED_CLAIMS #4).
  "equal cost"              — the cap factor f* was solved on ONE flat,
                              shock-free reference path. On simulated paths the
                              realised rate differs. "Reference-path
                              cost-matched" is the accurate name.
  "2.3x the interest"       — retracted by D-015 / DERIVATIONS P6: cost is
                              proportional to f, so a ratio quoted at the
                              illustrative f = 1.20 is a pricing result, not a
                              property of revenue-based repayment.
  "0.92 AUC"                — circular: the label was generated by a formula
                              over the same features (D-001).

DESIGN NOTE — why negation windows rather than a flat ban. Most of these
phrases MUST be sayable in order to disown them; a page that cannot print the
words "confidence interval" cannot tell the reader these are not confidence
intervals. So an occurrence passes when a disowning cue sits near it, and fails
when it stands alone. That keeps the honest usage legal and the assertive usage
failing.

The historical allow-list is deliberately narrow and is itself tested: an audit
document earns its exemption only by carrying a supersession banner. Otherwise
"it's historical" becomes the loophole that lets a retracted claim stay live.
"""
import os
import re

import pytest

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

#: Surfaces a reader or reviewer encounters as current claims.
LIVE_SURFACES = (
    "README.md",
    "RESEARCH_MANIFEST.md",
    "frontend/lab.html",
    "frontend/index.html",
    "backend/lab.py",
    "backend/money.py",
    "backend/financing_engine.py",
    "research/rbf_sim/README.md",
    "research/METRIC_DEFINITIONS.md",
)

#: Audit-trail documents. Exempt ONLY because they record what was believed and
#: why it changed. Each must carry a supersession/correction banner — asserted
#: by test_historical_documents_carry_a_supersession_banner below.
HISTORICAL = (
    "research/BASELINE_FINDINGS.md",
    "research/CORRECTED_CLAIMS.md",
    "research/PHASE0_AUDIT.md",
    "research/DECISION_LOG.md",
    "research/RESULTS_REGISTRY.md",
)

#: Frozen inputs. Editing these would desynchronise the spec version string
#: embedded in every canonical artifact, and P1-P7 are load-bearing proofs.
FROZEN = (
    "research/METHODOLOGY_SPEC.md",
    "research/DERIVATIONS.md",
)

#: Cues that turn an assertion into a disavowal.
#:
#: DIRECTIONAL AND TIGHT, and the first version of this test was neither. It
#: used a 240-char symmetric window including bare "not", which in dense
#: technical prose disowns essentially every match — the scanner passed the
#: whole repository while the very violations it was written for sat in
#: `lab.py` untouched. A scanner that cannot fail on the text that motivated it
#: is worse than no scanner, because it certifies.
#:
#: English disavowals put the negation immediately BEFORE the term ("this is
#: NOT a confidence interval") or a correction marker immediately AFTER
#: ("...conventional loan" — SUPERSEDED"). So: short windows, both sides.
NEGATION_BEFORE = (
    "not ", "not a", "n't ", "never ", "no longer", "rather than", "must not",
    "cannot ", "isn't", "aren't", "~~", "do not quote", "stop saying",
    "previously", "earlier claim", "was wrong", "the error", "avoid ",
    # Comparative disavowal: "...a stronger signal than any confidence
    # interval would be" argues against using the thing it names.
    "than any", "than a ", "instead of a ", "unlike ",
)
NEGATION_AFTER = (
    "supersede", "retract", "withdraw", "corrected", "was wrong", "is wrong",
    "demote", "circular", "do not quote", "no longer", "~~", "not a claim",
)
WINDOW_BEFORE = 90
WINDOW_AFTER = 60

#: (regex, why it is banned). Case-insensitive.
FORBIDDEN = (
    (r"instead of defaulting",
     "asserts revenue-contingency prevents default; closure_m7 is 100% incomplete"),
    (r"\bprevents? default|\bavoids? default|\bnever defaults?|\bcannot default",
     "no default model exists in this study; non-recovery is mechanical"),
    (r"\bconventional loan\b|\bconventional 12-month\b",
     "the 18% benchmark is an assumed input, not a sourced market rate"),
    (r"\bmarket[- ]rate\b|\brealistic (?:18|loan|rate|alternative)",
     "implies an externally sourced rate; none was sourced"),
    (r"confidence interval",
     "intervals are Monte Carlo over simulated paths, not population CIs"),
    (r"\bequal[- ]cost\b|\bequal effective cost\b",
     "say 'reference-path cost-matched'; f* was solved on one flat path"),
    (r"2\.3\s*[x×]\s*(?:the\s*)?interest",
     "retracted by D-015 / DERIVATIONS P6 as a price-structure conflation"),
    (r"0\.92\s*AUC|AUC\s*(?:of\s*)?0\.92",
     "circular metric; label generated by a formula over the same features"),
    # Scoped to OUTCOME guarantees. `money.settle` legitimately guarantees a
    # code invariant (`sum(settle(...)) <= cap_vnd`) that is proven by test and
    # survived mutation testing; banning that sense would punish a true
    # statement and teach the next reader to weaken it.
    (r"\bguarantees?d?\b(?=[^.]{0,90}(?:repay|recover|return|profit|outcome|"
     r"default|safe|cheap|afford))",
     "no seller- or provider-outcome is guaranteed on any path"),
    (r"\balways repays?\b|\brepays? in full\b(?! (?:only|when|where))",
     "full repayment is scenario- and horizon-conditional"),
    (r"\bproven safe\b|\bsafe for (?:providers|sellers)\b",
     "no safety claim is supported by simulated mechanics"),
)


def _read(rel):
    with open(os.path.join(REPO, rel), encoding="utf-8") as fh:
        return fh.read()


def _disowned(text, start, end):
    """True when a disavowal cue sits tight against the match, on either side."""
    before = text[max(0, start - WINDOW_BEFORE):start].lower()
    after = text[end:end + WINDOW_AFTER].lower()
    return (any(c in before for c in NEGATION_BEFORE)
            or any(c in after for c in NEGATION_AFTER))


@pytest.mark.parametrize("rel", LIVE_SURFACES)
def test_live_surfaces_do_not_overclaim(rel):
    path = os.path.join(REPO, rel)
    if not os.path.exists(path):
        pytest.skip(f"{rel} absent")
    text = _read(rel)
    violations = []
    for pattern, why in FORBIDDEN:
        for m in re.finditer(pattern, text, re.IGNORECASE):
            if _disowned(text, m.start(), m.end()):
                continue
            line = text.count("\n", 0, m.start()) + 1
            snippet = text[max(0, m.start() - 70):m.end() + 70].replace("\n", " ")
            violations.append(f"{rel}:{line}  {m.group(0)!r} — {why}\n      …{snippet}…")
    assert not violations, (
        "unqualified claim(s) on a public surface:\n  " + "\n  ".join(violations))


@pytest.mark.parametrize("rel", HISTORICAL)
def test_historical_documents_carry_a_supersession_banner(rel):
    """The exemption is earned, not granted.

    Without this, adding a file to HISTORICAL would be enough to smuggle a
    retracted claim back onto a surface a reader treats as current.
    """
    path = os.path.join(REPO, rel)
    if not os.path.exists(path):
        pytest.skip(f"{rel} absent")
    head = _read(rel)[:4000].lower()
    # Stems, not inflections. DECISION_LOG.md's banner reads "supersede them
    # with a new entry" — an earlier version of this list checked "superseded"
    # and "supersedes" and missed it by one character.
    cues = ("supersede", "correct", "retract", "withdraw",
            "audit trail", "do not quote", "demote", "historical", "append-only")
    assert any(c in head for c in cues), (
        f"{rel} is allow-listed as historical but its opening carries no "
        f"supersession/correction banner. Either add one or remove it from "
        f"HISTORICAL — the allow-list must not become a loophole.")


def test_frozen_documents_are_not_in_the_live_or_historical_lists():
    """The spec and the derivations are inputs, not surfaces to be edited.

    Their version strings are embedded in every canonical artifact and P1-P7 are
    referenced by the derivation tests. This test exists so a future edit that
    tries to 'fix the wording' in them has to consciously remove this guard.
    """
    for rel in FROZEN:
        assert rel not in LIVE_SURFACES, f"{rel} is frozen; do not scan-and-edit it"
        assert rel not in HISTORICAL, f"{rel} is frozen; do not scan-and-edit it"


#: The exact sentences this repository actually shipped, before D-037 removed
#: them. Verbatim, with their real surrounding context — a scanner tuned on
#: toy strings proves nothing about behaviour on dense prose, which is how the
#: first version of this file came to pass while the violations were live.
RETRACTED_COPY = (
    ('"why": "Revenue-based repayment extends the term when revenue falls "\n'
     '       "instead of defaulting. The extension is the provider\'s cost.",',
     "lab.py METRIC_DEFINITIONS.duration_months_mean"),
    ('"note": "A conventional 12-month amortizing loan at 18% nominal annual "\n'
     '        "rate. Not cost-matched; it is the external price reference."},',
     "lab.py ARMS FIX-B"),
    ("RBF at `f = 1.20` over a 12-month base case costs roughly 2.3x the "
     "interest of an 18% conventional loan. Mean payment burden is "
     "correspondingly higher for FIX-A (10.2%) than FIX-B (9.4%).",
     "BASELINE_FINDINGS F-2"),
)


@pytest.mark.parametrize("text,origin", RETRACTED_COPY)
def test_scanner_catches_the_copy_this_project_actually_retracted(text, origin):
    """The scanner must fail on the real sentences, not just on toy ones.

    This is the test that would have caught the first version of this file,
    whose negation window was so wide that `lab.py` scanned clean while both
    violations were still in it.
    """
    hits = [(p, w) for p, w in FORBIDDEN
            for mm in [re.search(p, text, re.IGNORECASE)] if mm
            and not _disowned(text, mm.start(), mm.end())]
    assert hits, (
        f"scanner does NOT catch retracted copy from {origin} — it would have "
        f"certified this text as safe:\n  {text}")


def test_negation_cues_do_not_disown_an_undisowned_sentence():
    """The other failure direction: cues so broad nothing ever fails."""
    planted = ("Revenue-based repayment extends the term when revenue falls "
               "instead of defaulting, and is cheaper than a conventional loan.")
    m = re.search(FORBIDDEN[0][0], planted, re.IGNORECASE)
    assert m and not _disowned(planted, m.start(), m.end()), \
        "NEGATION cues are too broad — they disown an undisowned sentence"
